// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMhI82uw0vfKqGun0i2vRR7l8_oAwcljs',
    appId: '1:1069838282623:web:3672978383e2fc8cb1b44a',
    messagingSenderId: '1069838282623',
    projectId: 'the-lift-club-7743f',
    authDomain: 'the-lift-club-7743f.firebaseapp.com',
    storageBucket: 'the-lift-club-7743f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9FJ95c-4bHjiUKAOvRUsFMjQHO9qcNcc',
    appId: '1:1069838282623:android:8d392525e57df547b1b44a',
    messagingSenderId: '1069838282623',
    projectId: 'the-lift-club-7743f',
    storageBucket: 'the-lift-club-7743f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCPlvJBo_W2FIsrmbR-cdzdXwu5zWS2CU',
    appId: '1:1069838282623:ios:9825f6eb4966e5b6b1b44a',
    messagingSenderId: '1069838282623',
    projectId: 'the-lift-club-7743f',
    storageBucket: 'the-lift-club-7743f.appspot.com',
    iosClientId: '1069838282623-gsbe7o5g62igo8l0ndgflrbqcb81nena.apps.googleusercontent.com',
    iosBundleId: 'za.co.wethinkcode.widgetsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCPlvJBo_W2FIsrmbR-cdzdXwu5zWS2CU',
    appId: '1:1069838282623:ios:9825f6eb4966e5b6b1b44a',
    messagingSenderId: '1069838282623',
    projectId: 'the-lift-club-7743f',
    storageBucket: 'the-lift-club-7743f.appspot.com',
    iosClientId: '1069838282623-gsbe7o5g62igo8l0ndgflrbqcb81nena.apps.googleusercontent.com',
    iosBundleId: 'za.co.wethinkcode.widgetsApp',
  );
}
